// <auto-generated />
using System;
using EFCoreDrillsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreDrillsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722142905_AddSoftDeleteFields")]
    partial class AddSoftDeleteFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreDrillsApi.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalGrade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingTrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrainingTrackId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnrollmentDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 0,
                            Status = "Active",
                            StudentId = 1,
                            TrainingTrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnrollmentDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 0,
                            Status = "Active",
                            StudentId = 2,
                            TrainingTrackId = 1
                        },
                        new
                        {
                            Id = 3,
                            EnrollmentDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 95,
                            Status = "Completed",
                            StudentId = 3,
                            TrainingTrackId = 2
                        },
                        new
                        {
                            Id = 4,
                            EnrollmentDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 0,
                            Status = "Active",
                            StudentId = 4,
                            TrainingTrackId = 2
                        },
                        new
                        {
                            Id = 5,
                            EnrollmentDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 0,
                            Status = "Dropped",
                            StudentId = 5,
                            TrainingTrackId = 3
                        });
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Ali"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sara Youssef"
                        });
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef@example.com",
                            FullName = "Youssef Ahmed",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona@example.com",
                            FullName = "Mona Hassan",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar@example.com",
                            FullName = "Omar Sayed",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila@example.com",
                            FullName = "Laila Mahmoud",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khaled@example.com",
                            FullName = "Khaled Ibrahim",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.StudentProfile", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Address = "Cairo",
                            DateOfBirth = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "",
                            NationalId = "29012345678901"
                        },
                        new
                        {
                            StudentId = 2,
                            Address = "Alexandria",
                            DateOfBirth = new DateTime(2001, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "",
                            NationalId = "29123456789012"
                        },
                        new
                        {
                            StudentId = 3,
                            Address = "Giza",
                            DateOfBirth = new DateTime(1999, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "",
                            NationalId = "29234567890123"
                        },
                        new
                        {
                            StudentId = 4,
                            Address = "Mansoura",
                            DateOfBirth = new DateTime(2002, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "",
                            NationalId = "29345678901234"
                        },
                        new
                        {
                            StudentId = 5,
                            Address = "Tanta",
                            DateOfBirth = new DateTime(2000, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "",
                            NationalId = "29456789012345"
                        });
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.TrainingTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("TrainingTracks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstructorId = 1,
                            Title = ".NET Full-Stack"
                        },
                        new
                        {
                            Id = 2,
                            InstructorId = 2,
                            Title = "Front-End React"
                        },
                        new
                        {
                            Id = 3,
                            InstructorId = 1,
                            Title = "Node.js Backend"
                        });
                });

            modelBuilder.Entity("EFCoreDrillsApi.PaymentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("PaymentSummaries");
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.Enrollment", b =>
                {
                    b.HasOne("EFCoreDrillsApi.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreDrillsApi.Models.TrainingTrack", "TrainingTrack")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrainingTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TrainingTrack");
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.StudentProfile", b =>
                {
                    b.HasOne("EFCoreDrillsApi.Models.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("EFCoreDrillsApi.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.TrainingTrack", b =>
                {
                    b.HasOne("EFCoreDrillsApi.Models.Instructor", "Instructor")
                        .WithMany("Tracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EFCoreDrillsApi.PaymentSummary", b =>
                {
                    b.HasOne("EFCoreDrillsApi.Models.Enrollment", "Enrollment")
                        .WithOne("PaymentSummary")
                        .HasForeignKey("EFCoreDrillsApi.PaymentSummary", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.Enrollment", b =>
                {
                    b.Navigation("PaymentSummary");
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.Instructor", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EFCoreDrillsApi.Models.TrainingTrack", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
